// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAOEpFcVql9dtYIQkgvzqGVFm77VB7w14',
    appId: '1:123240900148:web:d81c0f411242f89fb58c61',
    messagingSenderId: '123240900148',
    projectId: 'final-year-project-cms',
    authDomain: 'final-year-project-cms.firebaseapp.com',
    storageBucket: 'final-year-project-cms.firebasestorage.app',
    measurementId: 'G-TPNLZ4ZSK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHbZQX7AwmBDH69hKb4Jp6iX5XyY0OTcg',
    appId: '1:123240900148:android:044ca6200720b0f5b58c61',
    messagingSenderId: '123240900148',
    projectId: 'final-year-project-cms',
    storageBucket: 'final-year-project-cms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfSzeCk4L_EpyoL_vDlbEa5qlq1wBbVE',
    appId: '1:123240900148:ios:213b0c78695bb399b58c61',
    messagingSenderId: '123240900148',
    projectId: 'final-year-project-cms',
    storageBucket: 'final-year-project-cms.firebasestorage.app',
    androidClientId: '123240900148-073md62ehus5ln2d869acnjqflpgji9a.apps.googleusercontent.com',
    iosClientId: '123240900148-bih3m0b6flaqd8kpd24dsae1lq081rba.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnfSzeCk4L_EpyoL_vDlbEa5qlq1wBbVE',
    appId: '1:123240900148:ios:213b0c78695bb399b58c61',
    messagingSenderId: '123240900148',
    projectId: 'final-year-project-cms',
    storageBucket: 'final-year-project-cms.firebasestorage.app',
    androidClientId: '123240900148-073md62ehus5ln2d869acnjqflpgji9a.apps.googleusercontent.com',
    iosClientId: '123240900148-bih3m0b6flaqd8kpd24dsae1lq081rba.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAOEpFcVql9dtYIQkgvzqGVFm77VB7w14',
    appId: '1:123240900148:web:eb828bb89b215ef0b58c61',
    messagingSenderId: '123240900148',
    projectId: 'final-year-project-cms',
    authDomain: 'final-year-project-cms.firebaseapp.com',
    storageBucket: 'final-year-project-cms.firebasestorage.app',
    measurementId: 'G-9KQR3VV2KG',
  );

}