// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAOEpFcVql9dtYIQkgvzqGVFm77VB7w14',
    appId: '1:123240900148:web:e9e47e26f881e0b6b58c61',
    messagingSenderId: '123240900148',
    projectId: 'final-year-project-cms',
    authDomain: 'final-year-project-cms.firebaseapp.com',
    storageBucket: 'final-year-project-cms.firebasestorage.app',
    measurementId: 'G-05V3QZLK39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHbZQX7AwmBDH69hKb4Jp6iX5XyY0OTcg',
    appId: '1:123240900148:android:a5c802b1d8e05604b58c61',
    messagingSenderId: '123240900148',
    projectId: 'final-year-project-cms',
    storageBucket: 'final-year-project-cms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfSzeCk4L_EpyoL_vDlbEa5qlq1wBbVE',
    appId: '1:123240900148:ios:0f856249842d2bd2b58c61',
    messagingSenderId: '123240900148',
    projectId: 'final-year-project-cms',
    storageBucket: 'final-year-project-cms.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnfSzeCk4L_EpyoL_vDlbEa5qlq1wBbVE',
    appId: '1:123240900148:ios:0f856249842d2bd2b58c61',
    messagingSenderId: '123240900148',
    projectId: 'final-year-project-cms',
    storageBucket: 'final-year-project-cms.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAOEpFcVql9dtYIQkgvzqGVFm77VB7w14',
    appId: '1:123240900148:web:8f51c6c291464f1eb58c61',
    messagingSenderId: '123240900148',
    projectId: 'final-year-project-cms',
    authDomain: 'final-year-project-cms.firebaseapp.com',
    storageBucket: 'final-year-project-cms.firebasestorage.app',
    measurementId: 'G-1WEY45QBTF',
  );
}
